---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-time-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: epoch-time-api
  replicas: 1
  template:
    metadata:
      labels:
        app: epoch-time-api
    spec:
      containers:
      - image: public.ecr.aws/m4b9s1r9/time:latest
        name: epoch-time-api
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-time-api
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
  - port: 8080
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: epoch-time-api
